### ISSUE TITLE
Question: what am I doing wrong?

### ISSUE THREAD

**Issue by huyz** [jphalip/ideavim-switch#2]
I'm just trying to get it to work, but I can't seem to do it.

I installed the plugin:
![screenshot 2024-11-27T055852Z@2x](https://github.com/user-attachments/assets/a8e72c85-1763-4a4b-b4ad-25102af98a72)

I have this in `.ideavimrc`:
```vim
set switch

nmap <C-a> :Switch<CR>
nmap <C-x> :SwitchReverse<CR>

" Disabled
"map <C-A> <Action>(osmedile.intellij.stringmanip.IncrementAction)
```

My settings show that `^A` is given to Vim and `^X` has no conflict:
![screenshot 2024-11-27T055515Z@2x](https://github.com/user-attachments/assets/761d1c2c-b54d-43f9-82da-31cf24b3c334)

But when I have my cursor in a Java file inside the `public` or `private` word, whether in insert or normal mode, nothing happens when I hit `<C-a>` or `<C-x>`.

Anything else I could check?

**Comment by jphalip** [comment]
Hi there. Have you activated the definitions that you want to use?

Try to add this and then reload your ideavimrc:

```vim
let g:switch_definitions = "group:java"
```

**Comment by huyz** [comment]
Duh!
