### ISSUE TITLE
`:SwitchReverse` gives me `\bprivate\b`

### ISSUE THREAD

**Issue by huyz** [jphalip/ideavim-switch#3]
`:Switch` works great for me now.

But `:SwitchReverse` gives me `\bprivate\b`

**Comment by jphalip** [comment]
Ah, good catch. I can reproduce that issue. Let me work on a fix.

**Comment by jphalip** [comment]
@huyz I think I fixed the issue. Could you upgrade your plugin to version 1.0.1 and let me know if it works for you?

**Comment by huyz** [comment]
Works, thank you
